apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "otel-spring-example.fullname" . }}
  labels:
    {{- include "otel-spring-example.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "otel-spring-example.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "otel-spring-example.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "otel-spring-example.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}


  
          envFrom:
            
            
            - configMapRef:
                name: o11y-observability-configmap
  
  
          env:
            - name: SLEEP_SERVICE_URI
              value: http://otel-spring-example.{{ .Release.Namespace }}:8080/sleep



#          env:
#            - name: JAVA_TOOL_OPTIONS
#              value: "-javaagent:/usr/app/javaagent/opentelemetry-javaagent.jar"
#            - name: OTEL_EXPORTER_OTLP_ENDPOINT
#              value: "http://otel-collector.nsa2:4318"
#            - name: OTEL_LOGS_EXPORTER
#              value: "otlp"
#            - name: OTEL_TRACES_EXPORTER
#              value: "otlp"
#            - name: OTEL_METRICS_EXPORTER
#              value: "none"

          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- with .Values.metrics }}
            - name: metrics
              containerPort: {{ .port }}
              protocol: TCP
          {{- end }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
