{{- if .Values.gateway.enabled -}}
{{- $fullName := include "otel-spring-example.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ $fullName }}-route
  namespace: o11y
spec:
  parentRefs:
    - name: {{ .Values.gateway.parentRef.name }}
      namespace: {{ .Values.gateway.parentRef.namespace }}

{{- if .Values.gateway.hostname }}
  hostnames:
    - "{{ .Values.gateway.hostname }}"
{{- end }}

  rules:
    - matches:
        - path:
            type: PathPrefix
            value: {{ .Values.gateway.pathPrefix }}
      filters:
      - type: URLRewrite
        urlRewrite:
          path:
            type: ReplacePrefixMatch
            replacePrefixMatch: ""
      backendRefs:
        - name: {{ $fullName }}
          kind: Service
          port: {{ $svcPort }}
{{- end }}