apiVersion: v1
kind: Service
metadata:
  name: {{ include "otel-spring-example.fullname" . }}
  labels:
    {{- include "otel-spring-example.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.metrics.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics

  selector:
    {{- include "otel-spring-example.selectorLabels" . | nindent 4 }}
