apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: otel-spring-example-servicemonitor
  namespace: o11y
  labels:
    metrics-unit: o11y
    team: o11y
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: otel-spring-example
  endpoints:
    - port: metrics
      interval: 30s
      scheme: http
      path: /metrics